### ISSUE TITLE
"Tagged deploy" runs on new branches

### ISSUE THREAD

**Issue by Sigafoos** [exlibris-fed/exlibris#57]
See [this failed build](https://github.com/exlibris-fed/exlibris/runs/509725553?check_suite_focus=true). The trigger seems to not be doing what we want.

```yaml
on:
    create:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+
```
